# customer_code = "lev"
# environment = "prd"
# region = "sa-east-1"
# application = "levinux"
# runtime_python = "python3.12"
# handler_ec2 = "StartStopEc2.lambda_handler"
# handler_rds = "StartStopPostgreSQL.lambda_handler"
